openapi: 3.0.3
info:
  title: TheJebProject API Description
  description: |
    TheJebProject Backend API Description
  version: 0.1.0
paths:
  /auth/login:
    post:
      tags:
        - Authentication
      operationId: login
      description: |
        Authenticates the User.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
                  format: password
              required:
                - email
                - password
      responses:
        "200":
          description: Login Successful
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Tokens"
  /auth/register:
    post:
      tags:
        - Authentication
      operationId: register
      description: |
        Registers a new User.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
                email:
                  type: string
                password:
                  type: string
                  format: password
              required:
                - firstName
                - lastName
                - email
                - password
      responses:
        "200":
          description: |
            Registration Successful
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Tokens"
components:
  schemas:
    Tokens:
      type: object
      properties:
        accessToken:
          type: object
          properties:
            token:
              type: string
            expiresIn:
              type: integer
              format: int32
        refreshToken:
          type: object
          properties:
            token:
              type: string
            expiresIn:
              type: integer
              format: int32
